django_image/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_app.urls')),
    path('', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_app/urls.py
from django.urls import path
from . import views

app_name = 'image_app'

urlpatterns = [
    path('', views.list_image, name='list_image'),
    path('add_image/', views.add_image, name='add_image'),
    path('search/', views.search_feature, name='search-view'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_image/<int:id>', views.delete_image, name='delete_image'),
]

image_app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Image(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField()
    message = models.CharField(max_length=200)
    tarih = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.message

image_app/views.py
from datetime import datetime
from unidecode import unidecode
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.db.models import Q
from django.contrib.auth.models import User
from django.db.models.functions import Lower
from .models import Image
from django.urls import reverse_lazy

import html

def list_image(request):
    all_images = Image.objects.all()
    image_dict = {"images": all_images, "active_page": "list_image"}
    return render(request, 'image_app/list_image.html', context=image_dict)

@login_required(login_url='/login')
def add_image(request):
    if request.method == 'POST':
        image = request.FILES.get("image")
        message = request.POST.get("message")
        tarih = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        Image.objects.create(username=request.user, image=image, message=message, tarih=tarih)
        return redirect('image_app:list_image')
    else:
        return render(request, 'image_app/add_image.html', {'active_page': 'add_image'})


def normalize_query(query):
    return unidecode(query)


def search_feature(request):
    if request.method == 'POST':
        search_query = request.POST['search_query']
        normalized_query = html.unescape(search_query.lower())
        posts = Image.objects.filter(
            Q(message__icontains=normalized_query) |
            Q(username__username__icontains=normalized_query)
        )
        return render(request, 'image_app/search_results.html', {'query': search_query, 'posts': posts})
    else:
        return render(request, 'image_app/search_results.html', {})


@login_required
def delete_image(request, id):
    image = Image.objects.get(pk=id)
    if request.user == image.username:
        Image.objects.filter(id=id).delete()
        return redirect('image_app:list_image')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

def login_view(request):
    return render(request, 'registration/login.html', {'active_page': 'login'})

@login_required
def logout_view(request):
    return redirect('image_app:list_image')

def signup_view(request):
    return render(request, 'registration/signup.html', {'active_page': 'signup'})

image_app/templates/image_app/add_image.html
{% extends "base.html" %}

{% block content %}

<h2 class="container" style="width: 35%; font-size: 50px; color: rgb(155, 9, 9);">Fotoğraf Ekleme Sayfası</h2>


<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label style="font-size: 25px; color: rgb(155, 9, 9);" for="image" class="form-label">Fotoğraf:</label>
            <div class="border border-danger p-2 mb-2 border-opacity-50">
                <input type="file" class="form-control" id="image" name="image">
            </div>
        </div>

        <div class="mb-3">
            <label style="font-size: 25px; color: rgb(155, 9, 9);" for="message" class="form-label">Açıklama:</label>
            <div class="border border-danger p-2 mb-2 border-opacity-50">
                <textarea class="form-control" id="message" name="message" rows="5"></textarea>
            </div>  
        </div>

        <button type="submit" class="btn btn-danger">Kaydet</button>

    </form>
</div>

{% endblock %}

image_app/templates/image_app/list_image.html
{% extends "base.html" %}

{% block content %}
<div style="background-color: rgba(248, 248, 115, 0.856);">
    <h2 class="container" style="text-align: center; font-size: 50px; color: rgb(155, 9, 9);">Image Social</h2>
    <br><br>
    <div class="container">
        <ul>
            {% for image in images reversed %}

                <div class="card" style="background-color: rgb(255, 201, 101);">
                    <div style="display: flex;">
                        <div style="flex: 1; text-align: right;">
                            <ul style="list-style: none; padding-right: 100px;">
                                <li>
                                    <span style="font-size: 25px; color: rgb(155, 9, 9);">Kullanıcı:</span>
                                    <br>
                                    <span style="font-size: 25px;">{{image.username}}</span>
                                </li>
                            </ul>
                        </div>
                        <div style="flex: 1; text-align: center;">
                            <img src="{{ image.image.url }}" alt="Fotoğraf" style="width: 600px; height: auto;">
                        </div>
                        <div style="flex: 1;">
                            <ul style="list-style: none; padding-left: 20px;">
                                <li>
                                    <span style="font-size: 25px; color: rgb(155, 9, 9);">Açıklama:</span>
                                    <li>&nbsp;</li>
                                    <span style="font-size: 20px; color: black;">{{image.message}}</span>
                                </li>
                                <li>&nbsp;</li>
                                <li>
                                    <span style="font-size: 15px; color: black;">{{image.tarih}}</span>
                                </li>
                                <li>&nbsp;</li>
                                {% if image.username == user %}
                                    <a href="{% url 'image_app:delete_image' id=image.id %}" class="btn btn-danger">Gönderiyi Sil</a>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>

                {% if not forloop.last %}
                    <br><br>
                {% endif %}

            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

image_app/templates/image_app/search_results.html
{% extends "base.html" %}

{% block content %}

<h2 class="container" style="text-align: center;">Arama Sonuçları</h2>

<div class="container">
    
    {% if query %}
    
    <div>
        {% if posts %}
            {% for post in posts %}
                <div class="card" style="background-color: rgb(255, 201, 101);">
                    <div style="display: flex;">
                        <div style="flex: 1; text-align: right;">
                            <ul style="list-style: none; padding-right: 100px;">
                                <li>
                                    <span style="font-size: 25px; color: rgb(155, 9, 9);">Kullanıcı:</span>
                                    <br>
                                    <span style="font-size: 25px;">{{ post.username }}</span>
                                </li>
                            </ul>
                        </div>
                        <div style="flex: 1; text-align: center;">
                            <img src="{{ post.image.url }}" alt="Fotoğraf" style="width: 600px; height: auto;">
                        </div>
                        <div style="flex: 1;">
                            <ul style="list-style: none; padding-left: 20px;">
                                <li>
                                    <span style="font-size: 25px; color: rgb(155, 9, 9);">Açıklama:</span>
                                    <span style="font-size: 20px; color: black;">{{post.message}}</span>
                                </li>
                                <li>&nbsp;</li>
                                <li>
                                    <span style="font-size: 18px; color: rgb(155, 9, 9);">Kayıt Tarihi:</span>
                                    <span style="font-size: 15px; color: black;">{{post.tarih}}</span>
                                </li>
                                <li>&nbsp;</li>
                                <li>&nbsp;</li>
                                <li>&nbsp;</li>
                                {% if post.username.username == user.username %}
                                    <a href="{% url 'image_app:delete_image' id=post.id %}" class="btn btn-danger">Gönderiyi Sil</a>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>Aramanızla eşleşen sonuç bulunamadı.</h3>
        {% endif %}
    </div>

    {% else %}
        <h1>Lütfen aramak istediğiniz sorguyu giriniz.</h1>
    {% endif %}

</div>

{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
        crossorigin="anonymous">
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
        crossorigin="anonymous">
    </script>
    <title>Image Social</title>
    <style>
        .nav-link.font-bold {
            font-weight: bold;
            font-size: 20px;
        }
    </style>
    <meta charset="UTF-8">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-second fixed-top" style="background-color: orange;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'image_app:list_image' %}">Image Social</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navbarCollapse" 
                aria-controls="navbarCollapse" 
                aria-expanded="false" 
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if active_page == 'list_image' %}font-bold{% endif %}" 
                            aria-current="page" href="{% url 'image_app:list_image' %}">Fotoğraflar
                        </a>
                    </li>
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if active_page == 'add_image' %}font-bold{% endif %}" 
                            href="{% url 'image_app:add_image' %}">Ekle
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if active_page == 'logout' %}font-bold{% endif %}" 
                            href="{% url 'logout' %}?next=/">Çıkış Yap
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if active_page == 'login' %}font-bold{% endif %}" 
                            href="{% url 'login' %}">Giriş Yap
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if active_page == 'signup' %}font-bold{% endif %}" 
                            href="{% url 'image_app:signup' %}">Kayıt Ol
                        </a>
                    </li>
                </ul>
                <form class="d-flex" role="search" method="POST" action="{% url 'image_app:search-view' %}">
                    {% csrf_token %}
                    <input
                        class="form-control me-2"
                        type="search"
                        placeholder="Ara"
                        name="search_query"
                        required aria-label="Search"
                    >
                    <button class="btn btn-outline-success" type="submit">Ara</button>
                </form>
            </div>
        </div>
    </nav>
    

    <br><br><br><br>

    {% block content %}
    {% endblock %}

</body>
</html>